global:
  scrape_interval:     15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093


rule_files:
- 'rules/*'

scrape_configs:
  - job_name: couchbase
    file_sd_configs:
    - files:
      - targets.json
